# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-16 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Announcement',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
