# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180505_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillistsignup',
            name='email',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
